export const EVENT_UPDATE_USER_PROFILE = 'EVENT_UPDATE_USER_PROFILE';
export const EVENT_SERVER_PUSH_MESSAGE = 'EVENT_SERVER_PUSH_MESSAGE';
export const EVENT_UPDATE_FRIENDS = 'EVENT_UPDATE_FRIENDS';
export const EVENT_SERVER_REFRESH_SCORE = 'EVENT_SERVER_REFRESH_SCORE';
